name: Run All K6 Tests

on:
  push:
    branches:
      - master

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '0.49.0'

      - name: Create Reports Folder
        run: mkdir -p reports

      - name: Run All K6 Test Scripts
        run: |
          for script in test-scripts/*.test.js; do
            echo "Running $script"
            name=$(basename "$script" .test.js)
            k6 run --env TEST_NAME=$name "$script"
          done

      - name: Upload All HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: k6-html-reports
          path: reports/*.html
