name: Run All K6 Tests

on:
  push:
    branches:
      - master

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '0.49.0'

      - name: Install Node Dependencies
        run: npm install

      - name: Run All K6 Test Scripts
        run: |
          mkdir -p results
          for script in test-scripts/*.test.js; do
            name=$(basename "$script" .test.js)
            echo "Running $name"
            k6 run --out json=results/${name}.json "$script"
          done

      - name: Generate Summary Report
        run: node scripts/generate-summary-report.js

      - name: Upload Summary HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: k6-summary-report
          path: results/summary-report.html
